const FULL_ENTRY_FIELDS = [
  'id',
  'user_id',
  'content',
  'template_type',
  'created_at',
  'updated_at',
  'emotion_display',
  'emotions',
  'emotion_confidence',
  'image_urls',
  'annotations',
  'people_involved',
  'category_tags',
  'core_needs',
  'current_thought',
  'current_behavior',
  'handling_rating',
  'cognitive_distortion_type',
  'body_sensations',
  'cognitive_analysis',
  'reflection_insight',
  'entry_summary',
  'overall_state_score',
  'theme_hints',
  'covered_by_letter_id',
]

export const JOURNAL_ENTRY_FULL_SELECT = FULL_ENTRY_FIELDS.join(', ')
